version: "3.9"

services:
  api:
    build: .
    container_name: book_container
    image: books-api
    ports:
      - '8000:8000'
    volumes:
      - ./:/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --reload